server:
  port: 8888
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/JavaEE
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 88888888

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # ??MP????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      table-prefix: retailer, fruit  # ????????
      id-type: auto